CREATE TABLE IF NOT EXISTS message
(
    id     INT auto_increment NOT NULL,
    msg           VARCHAR(4000)  NOT NULL
);

INSERT INTO MESSAGE VALUES ( null,'1');
INSERT INTO MESSAGE VALUES ( null,'2');
INSERT INTO MESSAGE VALUES ( null,'3');
INSERT INTO MESSAGE VALUES ( null,'4');